name: .NET Core Desktop

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2016

    env:
      Solution_Name: SOAPHound.sln  # 替换为你的解决方案文件名

    steps:
    # 检出代码
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # 安装 .NET Core SDK
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # 设置 MSBuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # 还原 NuGet 包
    - name: Restore NuGet Packages
      run: |
        dotnet restore ${{ github.workspace }}\${{ env.Solution_Name }}

    # 构建项目
    - name: Build the application
      run: |
        msbuild ${{ github.workspace }}\${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }}

    # 上传构建结果
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SOAPHound
        path: ${{ github.workspace }}\bin\${{ matrix.configuration }}
